import { env } from 'node:process';
import {
	Colors,
	ContainerBuilder,
	EmbedBuilder,
	type GuildMember,
	SeparatorBuilder,
	SeparatorSpacingSize,
	subtext,
	TextDisplayBuilder,
	TimestampStyles,
	time,
	type User,
} from 'discord.js';
import type { Client } from '.';

/**
 * The base for all executable classes.
 */
export abstract class Base {
	public constructor(protected readonly client: Client) {}

	/**
	 * @returns Embed with a presetted footer and timestamp.
	 */
	protected get embed() {
		return new EmbedBuilder()
			.setColor(Colors.Blurple)
			.setTimestamp()
			.setFooter({ text: `Version ${env.npm_package_version}`, iconURL: this.client.user?.displayAvatarURL() });
	}

	/**
	 * @returns Embed with presetted data and a user.
	 */
	protected userEmbed(user: User | GuildMember) {
		return this.embed.setAuthor({
			name: user.displayName,
			iconURL: user.displayAvatarURL(),
		});
	}

	/**
	 * @returns Embed with presetted data for user errors.
	 */
	protected userEmbedError(user: User | GuildMember, title = 'You Hit an Error!') {
		return this.userEmbed(user).setColor(Colors.DarkRed).setTitle(title);
	}

	/**
	 * @returns A container component with presetted data.
	 */
	protected container(builder: ContainerBuilder | ((cont: ContainerBuilder) => ContainerBuilder)) {
		const cont = typeof builder === 'function' ? builder(new ContainerBuilder()) : builder;

		return cont
			.setAccentColor(cont.data.accent_color ?? Colors.Blurple)
			.addSeparatorComponents(new SeparatorBuilder().setSpacing(SeparatorSpacingSize.Large).setDivider(true))
			.addTextDisplayComponents(
				new TextDisplayBuilder().setContent(
					subtext(
						`${this.client.user?.displayName}: Version ${env.npm_package_version} • ${time(new Date(), TimestampStyles.ShortDateMediumTime)}`,
					),
				),
			);
	}

	protected dynamicCustomId(id: string) {
		return `{dynamic}_${id}`;
	}

	protected extractCustomId(value: string, dynamicValueRequired: true): Required<ExtractCustomId>;
	protected extractCustomId(value: string, dynamicValueRequired: false): ExtractCustomId;
	protected extractCustomId(value: string, dynamicValueRequired?: boolean): Required<ExtractCustomId> | ExtractCustomId;

	// Partially generated by ChatGPT 3.5.
	protected extractCustomId(value: string, dynamicValueRequired = false): Required<ExtractCustomId> | ExtractCustomId {
		// Define a regular expression to match "{dynamicValue}_".
		const regex = /{([^}]+)}_/;

		// Execute the regular expression and get the captured value.
		const match = regex.exec(value);

		// Check if there is a match and return the captured value.
		const dynamicValue = match?.at(1);

		return {
			// Add 3 due to the characters surrounding "dynamic" (i.e "{}_").
			customId: dynamicValue ? this.dynamicCustomId(value.slice(dynamicValue.length + 3)) : value,
			...((dynamicValue || dynamicValueRequired) && { dynamicValue }),
		};
	}

	protected customId<T extends string, U>(id: T, dynamicValue?: U) {
		return dynamicValue !== undefined && dynamicValue !== null ? `{${dynamicValue}}_${id}` : id;
	}

	// The return type is `any` because the function should be able to return anything or nothing.
	// biome-ignore lint/suspicious/noExplicitAny: Type `unknown` is more suitable but gave errors.
	public abstract execute(...parameters: unknown[]): any;
}

interface ExtractCustomId {
	customId: string;
	dynamicValue?: string;
}
