publicHoistPattern:
  - "@types/node" # Required for only one installation of types to be present in all packages.

packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
