interface ExtractCustomId {
	customId: string;
	dynamicValue?: string;
}

export function dynamicCustomId(id: string) {
	return `{dynamic}_${id}`;
}

export function extractCustomId(value: string, dynamicValueRequired: true): Required<ExtractCustomId>;
export function extractCustomId(value: string, dynamicValueRequired: false): ExtractCustomId;
export function extractCustomId(
	value: string,
	dynamicValueRequired?: boolean,
): Required<ExtractCustomId> | ExtractCustomId;

// Partially generated by ChatGPT 3.5.
export function extractCustomId(
	value: string,
	dynamicValueRequired = false,
): Required<ExtractCustomId> | ExtractCustomId {
	// Define a regular expression to match "{dynamicValue}_".
	const regex = /{([^}]+)}_/;

	// Execute the regular expression and get the captured value.
	const match = regex.exec(value);

	// Check if there is a match and return the captured value.
	const dynamicValue = match?.at(1);

	return {
		// Add 3 due to the characters surrounding "dynamic" (i.e "{}_").
		customId: dynamicValue ? dynamicCustomId(value.slice(dynamicValue.length + 3)) : value,
		...((dynamicValue || dynamicValueRequired) && { dynamicValue }),
	};
}

export function customId<T extends string, U>(id: T, dynamicValue?: U) {
	return dynamicValue !== undefined && dynamicValue !== null ? `{${dynamicValue}}_${id}` : id;
}
